### ISSUE TITLE
Agg-Sharp Tests Failing on Windows 10 Insider Preview 17713.rs5_release.180706

### ISSUE THREAD

**Issue by viniciusmiguel** [MatterHackers/agg-sharp#1014]
MouserInteractionTests.DoClickButtonInWindow:
```
System.AggregateException : One or more errors occurred.
  ----> NUnit.Framework.AssertionException :   Got left button click
  Expected: True
  But was:  False

   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at NUnit.ApplicationDomain.TaskWaitTestResultHandler.Process(Task task)
   at NUnit.ApplicationDomain.Internal.InDomainTestMethodRunner.RunSetupAndTest(TestMethodInformation testMethodInfo, Object instance)
   at NUnit.ApplicationDomain.Internal.InDomainTestMethodRunner.Execute(TestMethodInformation testMethodInfo)
   at NUnit.ApplicationDomain.Internal.InDomainTestMethodRunner.Execute(TestMethodInformation testMethodInfo)
   at NUnit.ApplicationDomain.Internal.ParentAppDomainRunner.Run(ITest test, Type appDomainFactoryType)
   at NUnit.Framework.RunInApplicationDomainAttribute.RunInApplicationDomain(ITest testDetails)
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.Execute(TestExecutionContext context)
--AssertionException
   at NUnit.Framework.Assert.ReportFailure(String message)
   at NUnit.Framework.Assert.That[TActual](TActual actual, IResolveConstraint expression, String message, Object[] args)
   at MatterHackers.Agg.UI.Tests.MouseInteractionTests.<>c__DisplayClass0_0.<DoClickButtonInWindow>b__0(AutomationRunner testRunner) in C:\Users\Vinicius.Miguel\Source\Repos\MatterControl\Submodules\agg-sharp\Tests\Agg.Tests\Agg.UI\MouseInteractionTests.cs:line 64
   at MatterHackers.GuiAutomation.AutomationRunner.<>c__DisplayClass71_0.<ShowWindowAndExecuteTests>b__1() in C:\Users\Vinicius.Miguel\Source\Repos\MatterControl\Submodules\agg-sharp\GuiAutomation\AutomationRunner.cs:line 1089
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at MatterHackers.Agg.UI.Tests.MouseInteractionTests.<DoClickButtonInWindow>d__0.MoveNext() in C:\Users\Vinicius.Miguel\Source\Repos\MatterControl\Submodules\agg-sharp\Tests\Agg.Tests\Agg.UI\MouseInteractionTests.cs:line 90
```

**This is one example.
I identified the issue when I tried to install the MatterControll Beta and the UI was totally unresponsive.

Consequently, the MatterControll tests are failing too:**

```

System.AggregateException : One or more errors occurred.
  ----> System.Exception : ClickByName Failed: Named GuiWidget not found [-Temporary Row Item Collection]
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at NUnit.ApplicationDomain.TaskWaitTestResultHandler.Process(Task task)
   at NUnit.ApplicationDomain.Internal.InDomainTestMethodRunner.RunSetupAndTest(TestMethodInformation testMethodInfo, Object instance)
   at NUnit.ApplicationDomain.Internal.InDomainTestMethodRunner.Execute(TestMethodInformation testMethodInfo)
   at NUnit.ApplicationDomain.Internal.InDomainTestMethodRunner.Execute(TestMethodInformation testMethodInfo)
   at NUnit.ApplicationDomain.Internal.ParentAppDomainRunner.Run(ITest test, Type appDomainFactoryType)
   at NUnit.Framework.RunInApplicationDomainAttribute.RunInApplicationDomain(ITest testDetails)
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.Execute(TestExecutionContext context)
--Exception
   at MatterHackers.GuiAutomation.AutomationRunner.ClickByName(String widgetName, SearchRegion searchRegion, Point2D offset, ClickOrigin origin, Boolean isDoubleClick) in C:\Users\Vinicius.Miguel\Source\Repos\MatterControl\Submodules\agg-sharp\GuiAutomation\AutomationRunner.cs:line 716
   at MatterHackers.GuiAutomation.AutomationRunner.DoubleClickByName(String widgetName, SearchRegion searchRegion, Point2D offset, ClickOrigin origin) in C:\Users\Vinicius.Miguel\Source\Repos\MatterControl\Submodules\agg-sharp\GuiAutomation\AutomationRunner.cs:line 802
   at MatterHackers.MatterControl.Tests.Automation.MatterControlUtilities.NavigateToFolder(AutomationRunner testRunner, String libraryRowItemName) in C:\Users\Vinicius.Miguel\Source\Repos\MatterControl\Tests\MatterControl.Tests\MatterControl\MatterControlUtilities.cs:line 466
   at MatterHackers.MatterControl.Tests.Automation.LibraryDownloadsTests.<>c.<CreateFolder>b__6_0(AutomationRunner testRunner) in C:\Users\Vinicius.Miguel\Source\Repos\MatterControl\Tests\MatterControl.AutomationTests\LibraryDownloadsTest.cs:line 138
   at MatterHackers.GuiAutomation.AutomationRunner.<>c__DisplayClass71_0.<ShowWindowAndExecuteTests>b__1() in C:\Users\Vinicius.Miguel\Source\Repos\MatterControl\Submodules\agg-sharp\GuiAutomation\AutomationRunner.cs:line 1089
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at MatterHackers.MatterControl.Tests.Automation.MatterControlUtilities.<RunTest>d__49.MoveNext() in C:\Users\Vinicius.Miguel\Source\Repos\MatterControl\Tests\MatterControl.Tests\MatterControl\MatterControlUtilities.cs:line 673
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at MatterHackers.MatterControl.Tests.Automation.LibraryDownloadsTests.<CreateFolder>d__6.MoveNext() in C:\Users\Vinicius.Miguel\Source\Repos\MatterControl\Tests\MatterControl.AutomationTests\LibraryDownloadsTest.cs:line 132

   Overriding StaticData: C:\Users\Vinicius.Miguel\Source\Repos\MatterControl\StaticData
   Overriding ApplicationUserDataPath: C:\Users\Vinicius.Miguel\Source\Repos\MatterControl\Tests\temp\2018-08-14T17-29-03\Test0
Time to '': 928
```

**Comment by viniciusmiguel** [comment]
[BorderTestLeft.txt](https://github.com/MatterHackers/agg-sharp/files/2287559/BorderTestLeft.txt)

**Comment by larsbrubaker** [comment]
Closing as stale. This was against a 2018 Windows Insider preview build and the NUnit-era test infrastructure, which no longer exists — the test suite has since moved to TUnit and the automation framework has been heavily reworked. If anything similar reproduces on a current build, please open a fresh issue.
